server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true # Hibernate? ?? SQL?? ????.
    properties:
      hibernate:
        format_sql: true # ??? ????.
    hibernate:
#      ddl-auto: none # Hibernate ??? ? none?? ????.
      ddl-auto: create # ?? ???

logging:
  level:
    '[org.hibernate.type]': TRACE # Binding ??? ???